# Site settings
title: Michael Araya
email: michaelseifuaraya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rails Developer || Gent
baseurl:  ""
url:  "https://michaelarayabe.github.io"
twitter_username: mikaseifu
github_username:  michaelarayabe

# Build settings
markdown: kramdown

highlighter: rouge

# # Pagination
# paginate: 15
# paginate_path: "/blog/page:num/"
# gems: 
#   - jekyll-paginate

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/



